# Generated by Django 5.0.6 on 2024-07-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assign Invoice',
            new_name='assignInvoice',
        ),
    ]
